### ISSUE TITLE
Add ANTLR plugin logo

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-antlr4#1]
Logo from JetBrains plugin: https://plugins.jetbrains.com/plugin/7358-antlr-v4
SVG file: [ANTLR_logo.zip](https://github.com/consulo/consulo-antlr4/files/7480439/ANTLR_logo.zip)
![изображение](https://user-images.githubusercontent.com/16825982/140455233-cea814f5-09ef-449a-9558-140e4030780e.png)

**Comment by VISTALL** [comment]
Original repo contains it (check fork info)

https://github.com/antlr/intellij-plugin-v4/blob/master/src/main/resources/META-INF/pluginIcon.svg

**Comment by unv-unv** [comment]
Good. Let's display it :)

**Comment by VISTALL** [comment]
I made icon bigger due Consulo restriction. Added
